nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['http://localhost:3000', 'https://localhost:3000', 'http://localhost', 'https://localhost', 'http://localhost:8080']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Preload', 'Fields', 'X-Requested-With']
        expose_headers: ['Link']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/': ~
