name: CI
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  lint-docker:
    name: Docker Linting
    permissions:
      contents: read
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || contains(github.event.pull_request.changed_files.*.filename, 'Dockerfile') || contains(github.event.pull_request.changed_files.*.filename, 'compose')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Lint Dockerfiles
        uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true
          verbose: true
          failure-threshold: error
      
      - name: Validate Docker Compose files
        run: |
          docker compose -f compose.yaml config -q
          docker compose -f compose.yaml -f compose.override.yaml config -q
          docker compose -f compose.yaml -f compose.prod.yaml config -q

  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-suite:
          - name: "PHP Tests & Analysis"
            commands: |
              make test-coverage-check
              make lint-phpstan
              docker compose exec -T php vendor/bin/phpmd src text phpmd.xml
              docker compose exec -T php vendor/bin/php-cs-fixer fix --dry-run --verbose --diff
              docker compose exec -T php bin/console -e test doctrine:schema:validate
          - name: "Frontend Tests & Analysis"
            commands: |
              make test-frontend-coverage-check
              make lint-eslint
              docker compose exec -T pwa npx tsc --noEmit
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        uses: docker/bake-action@v6
        with:
          pull: true
          load: true
          files: |
            compose.yaml
            compose.override.yaml
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{github.ref}},mode=max

      - name: Start services
        run: docker compose up --wait --no-build

      - name: Wait for services to stabilize
        run: sleep 10

      - name: Verify services health
        run: |
          echo "=== Services Status ==="
          docker compose ps
          echo "=== Health Checks ==="
          docker compose exec -T php curl -f http://localhost:2019/metrics || echo "Caddy metrics check failed"
          curl -f http://localhost --max-time 30 || echo "HTTP check failed"
          curl -fk https://localhost --max-time 30 || echo "HTTPS check failed"

      - name: Prepare test environment
        run: |
          docker compose exec -T php bin/console -e test doctrine:database:create --if-not-exists
          docker compose exec -T php bin/console -e test doctrine:migrations:migrate --no-interaction

      - name: Run test suite
        run: ${{ matrix.test-suite.commands }}

      - name: Upload PHP Coverage
        if: matrix.test-suite.name == 'PHP Tests & Analysis'
        uses: codecov/codecov-action@v4
        with:
          file: ./api/var/coverage/clover.xml
          flags: php
          name: php-coverage
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload Frontend Coverage
        if: matrix.test-suite.name == 'Frontend Tests'
        uses: codecov/codecov-action@v4
        with:
          file: ./pwa/coverage/lcov.info
          flags: frontend
          name: frontend-coverage
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        uses: docker/bake-action@v6
        with:
          pull: true
          load: true
          files: |
            compose.yaml
            compose.override.yaml
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main

      - name: Start services
        run: docker compose up --wait --no-build

      - name: Prepare test environment
        run: |
          docker compose exec -T php bin/console -e test doctrine:database:create --if-not-exists
          docker compose exec -T php bin/console -e test doctrine:migrations:migrate --no-interaction

      - name: Run architectural validation
        run: make lint-deptrac

      - name: Validate complete system
        run: |
          echo "🔍 Running complete system validation..."
          
          # API Health Check
          for i in {1..3}; do
            if curl -f http://localhost/api/greetings --max-time 10; then
              echo "✅ API is responding"
              break
            elif [ $i -eq 3 ]; then
              echo "❌ API health check failed after 3 attempts"
              docker compose logs api
              exit 1
            else
              echo "⏳ API check attempt $i failed, retrying..."
              sleep 5
            fi
          done
          
          # PWA Health Check  
          for i in {1..3}; do
            if curl -f http://localhost:3000 --max-time 10; then
              echo "✅ PWA is responding"
              break
            elif [ $i -eq 3 ]; then
              echo "❌ PWA health check failed after 3 attempts"
              docker compose logs pwa
              exit 1
            else
              echo "⏳ PWA check attempt $i failed, retrying..."
              sleep 5
            fi
          done

  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-latest
    needs: [lint-docker, build-and-test, integration-tests]
    if: always()
    steps:
      - name: Check quality gate
        run: |
          if [[ "${{ needs.lint-docker.result }}" == "success" && 
                "${{ needs.build-and-test.result }}" == "success" && 
                "${{ needs.integration-tests.result }}" == "success" ]]; then
            echo "✅ All quality checks passed!"
            echo "📊 100% coverage maintained across PHP and Frontend"
            echo "🏗️ Architecture validation successful"
            echo "🐳 Docker configuration validated"
          else
            echo "❌ Quality gate failed!"
            echo "Lint Docker: ${{ needs.lint-docker.result }}"
            echo "Build & Test: ${{ needs.build-and-test.result }}"
            echo "Integration: ${{ needs.integration-tests.result }}"
            exit 1
          fi