name: Frontend Linting

on:
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build Docker images
        run: |
          docker compose build pwa --pull
      
      - name: Start services
        run: docker compose up pwa -d
      
      - name: Install dependencies
        run: docker compose exec -T pwa pnpm install
      
      - name: Run ESLint (with --fix)
        run: docker compose exec -T pwa pnpm lint --fix

  typescript:
    name: TypeScript Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build Docker images
        run: |
          docker compose build pwa --pull
      
      - name: Start services
        run: docker compose up pwa -d
      
      - name: Install dependencies
        run: docker compose exec -T pwa pnpm install
      
      - name: Run TypeScript check
        run: docker compose exec -T pwa npx tsc --noEmit

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build Docker images
        run: |
          docker compose build pwa --pull
      
      - name: Start services
        run: docker compose up pwa -d
      
      - name: Install dependencies
        run: docker compose exec -T pwa pnpm install
      
      - name: Run tests with coverage check (100% required)
        run: docker compose exec -T pwa pnpm test:coverage:check
      
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        if: always()
        with:
          file: ./pwa/coverage/lcov.info
          flags: frontend
          name: frontend-coverage